build.debug:
	cargo build --target x86_64-pc-windows-gnu

build.release:
	cargo build --target x86_64-pc-windows-gnu --release

build.win.debug:
	cargo build --target x86_64-pc-windows-msvc

build.win.release:
	cargo build --target x86_64-pc-windows-msvc --release
