// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearProfile(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetAlwaysOnTop():Promise<boolean>;

export function GetCabControlState():Promise<main.Interop_Cab_ControlState>;

export function GetControllerConfiguration(arg1:string):Promise<main.Interop_ControllerConfiguration>;

export function GetControllers():Promise<Array<main.Interop_GenericController>>;

export function GetLastInstalledModVersion():Promise<string>;

export function GetLatestReleaseVersion():Promise<string>;

export function GetPreferredControlMode():Promise<string>;

export function GetProfiles():Promise<Array<main.Interop_Profile>>;

export function GetSelectedProfile():Promise<main.Interop_SelectedProfileInfo>;

export function GetSelectedProfiles():Promise<Record<string, main.Interop_SelectedProfileInfo>>;

export function GetSharedProfiles():Promise<Array<main.Interop_SharedProfile>>;

export function GetTSWAPIKeyLocation():Promise<string>;

export function GetTheme():Promise<string>;

export function GetVersion():Promise<string>;

export function HasNewerVersion():Promise<boolean>;

export function ImportProfile():Promise<void>;

export function ImportSharedProfile(arg1:main.Interop_SharedProfile):Promise<void>;

export function InstallTrainSimWorldMod():Promise<void>;

export function LastRawEvent():Promise<main.Interop_RawEvent>;

export function LoadConfiguration():Promise<void>;

export function OpenConfigDirectory():Promise<void>;

export function OpenNewProfileBuilder():Promise<void>;

export function OpenNewProfileBuilderForUsbID(arg1:string):Promise<void>;

export function OpenProfileBuilder(arg1:string):Promise<void>;

export function ResetCabControlState():Promise<void>;

export function SaveCalibration(arg1:main.Interop_ControllerCalibration):Promise<void>;

export function SaveLogs(arg1:Array<string>):Promise<void>;

export function SaveProfileForSharing(arg1:string):Promise<void>;

export function SaveProfileForSharingWithControllerInformation(arg1:string,arg2:string):Promise<void>;

export function SelectProfile(arg1:string,arg2:string):Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetLastInstalledModVersion(arg1:string):Promise<void>;

export function SetPreferredControlMode(arg1:string):Promise<void>;

export function SetTSWAPIKeyLocation(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SubscribeRaw(arg1:string):Promise<void>;

export function UnsubscribeRaw():Promise<void>;

export function UpdateApp():Promise<boolean>;
