// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearProfile(arg1) {
  return window['go']['main']['App']['ClearProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetAlwaysOnTop() {
  return window['go']['main']['App']['GetAlwaysOnTop']();
}

export function GetCabControlState() {
  return window['go']['main']['App']['GetCabControlState']();
}

export function GetControllerConfiguration(arg1) {
  return window['go']['main']['App']['GetControllerConfiguration'](arg1);
}

export function GetControllers() {
  return window['go']['main']['App']['GetControllers']();
}

export function GetLastInstalledModVersion() {
  return window['go']['main']['App']['GetLastInstalledModVersion']();
}

export function GetLatestReleaseVersion() {
  return window['go']['main']['App']['GetLatestReleaseVersion']();
}

export function GetPreferredControlMode() {
  return window['go']['main']['App']['GetPreferredControlMode']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSelectedProfiles() {
  return window['go']['main']['App']['GetSelectedProfiles']();
}

export function GetSharedProfiles() {
  return window['go']['main']['App']['GetSharedProfiles']();
}

export function GetTSWAPIKeyLocation() {
  return window['go']['main']['App']['GetTSWAPIKeyLocation']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasNewerVersion() {
  return window['go']['main']['App']['HasNewerVersion']();
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function ImportSharedProfile(arg1) {
  return window['go']['main']['App']['ImportSharedProfile'](arg1);
}

export function InstallTrainSimWorldMod() {
  return window['go']['main']['App']['InstallTrainSimWorldMod']();
}

export function LoadConfiguration() {
  return window['go']['main']['App']['LoadConfiguration']();
}

export function OpenConfigDirectory() {
  return window['go']['main']['App']['OpenConfigDirectory']();
}

export function OpenNewProfileBuilder() {
  return window['go']['main']['App']['OpenNewProfileBuilder']();
}

export function OpenNewProfileBuilderForUsbID(arg1) {
  return window['go']['main']['App']['OpenNewProfileBuilderForUsbID'](arg1);
}

export function OpenProfileBuilder(arg1) {
  return window['go']['main']['App']['OpenProfileBuilder'](arg1);
}

export function ResetCabControlState() {
  return window['go']['main']['App']['ResetCabControlState']();
}

export function SaveCalibration(arg1) {
  return window['go']['main']['App']['SaveCalibration'](arg1);
}

export function SaveLogs(arg1) {
  return window['go']['main']['App']['SaveLogs'](arg1);
}

export function SaveProfileForSharing(arg1) {
  return window['go']['main']['App']['SaveProfileForSharing'](arg1);
}

export function SaveProfileForSharingWithControllerInformation(arg1, arg2) {
  return window['go']['main']['App']['SaveProfileForSharingWithControllerInformation'](arg1, arg2);
}

export function SelectCommAPIKeyFile() {
  return window['go']['main']['App']['SelectCommAPIKeyFile']();
}

export function SelectProfile(arg1, arg2) {
  return window['go']['main']['App']['SelectProfile'](arg1, arg2);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetLastInstalledModVersion(arg1) {
  return window['go']['main']['App']['SetLastInstalledModVersion'](arg1);
}

export function SetPreferredControlMode(arg1) {
  return window['go']['main']['App']['SetPreferredControlMode'](arg1);
}

export function SetTSWAPIKeyLocation(arg1) {
  return window['go']['main']['App']['SetTSWAPIKeyLocation'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SubscribeRaw(arg1) {
  return window['go']['main']['App']['SubscribeRaw'](arg1);
}

export function TypestubGetRawEvent() {
  return window['go']['main']['App']['TypestubGetRawEvent']();
}

export function TypestubGetSelectedProfile() {
  return window['go']['main']['App']['TypestubGetSelectedProfile']();
}

export function UnsubscribeRaw() {
  return window['go']['main']['App']['UnsubscribeRaw']();
}

export function UpdateApp() {
  return window['go']['main']['App']['UpdateApp']();
}
